version: '3'

networks:
  boa-entrega:

volumes:
  postgres:
    driver: local

services:
  ### Microservices
  customer-app:
    build:
      context: ./backend/
      dockerfile: customer.Dockerfile
    container_name: customer-app
    ports:
      - "8081:8081"
    networks:
      - boa-entrega
    depends_on:
      - postgres

  supplier-app:
    build:
      context: ./backend/
      dockerfile: supplier.Dockerfile
    container_name: supplier-app
    ports:
      - "8082:8082"
    networks:
      - boa-entrega
    environment:
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASS: admin
    depends_on:
      - postgres


  ### Shared database
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - boa-entrega
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./config/postgres/create_all_databases.sh:/docker-entrypoint-initdb.d/create_all_databases.sh
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: boaentrega
      POSTGRES_PASSWORD: boaentrega


  ### AWS local resources
#  localstack:
#    image: localstack/localstack:0.14.2
#    container_name: localstack
#    ports:
#      - "4566:4566"
#    networks:
#      - boa-entrega
#    environment:
#      SERVICES: sns
#      HOSTNAME: localstack
#      HOSTNAME_EXTERNAL: localstack


  ### API Gateway
  kong:
    build:
      context: ./config/kong/
      dockerfile: Dockerfile
    container_name: kong
    user: kong
#    command:
#      - http :8001/config config=@/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    networks:
      - boa-entrega
    volumes:
      - ./config/kong/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PLUGINS: bundled,jwt-keycloak
    depends_on:
      - postgres


  ### Auth server
  keycloak:
    build:
      context: ./config/keycloak/
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8080:8080"
    networks:
      - boa-entrega
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: boaentrega
      DB_PASSWORD: boaentrega
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
