--- 
_format_version: "1.1"
services: 
  - 
    host: keycloak
    name: keycloak
    port: 8080
    protocol: http
    routes: 
      - 
        name: token
        paths: 
          - /realms/master
        strip_path: false
  - 
    host: customer-app
    name: customer
    port: 8081
    protocol: http
    routes: 
      - 
        name: customer
        paths: 
          - /api/customer
        plugins: 
          - 
            config: 
              allowed_iss: 
                - "http://keycloak:8080/realms/master"
                - "http://localhost:8080/realms/master"
              realm_roles: 
                - customer
              well_known_template: "http://keycloak:8080/realms/master/.well-known/openid-configuration"
            name: jwt-keycloak
        strip_path: false
      - 
        name: customer_swagger
        paths: 
          - /customer
        strip_path: false
  - 
    host: supplier-app
    name: supplier
    port: 8082
    protocol: http
    routes: 
      - 
        name: supplier
        paths: 
          - /api/security
          - /api/warehouse
        plugins: 
          - 
            config: 
              allowed_iss: 
                - "http://keycloak:8080/realms/master"
                - "http://localhost:8080/realms/master"
              realm_roles: 
                - supplier
              well_known_template: "http://keycloak:8080/realms/master/.well-known/openid-configuration"
            name: jwt-keycloak
        strip_path: false
      - 
        name: supplier_swagger
        paths: 
          - /supplier
        strip_path: false
