_format_version: "1.1"

services:
  - host: keycloak
    name: keycloak
    port: 8080
    protocol: http
    routes:
      - name: token
        strip_path: false
        paths:
          - /realms/master

  - host: customer-app
    name: customer
    port: 8081
    protocol: http
    routes:
      - name: customer
        strip_path: false
        paths:
          - /customer
          - /api/customer
    plugins:
      - name: jwt-keycloak
        config:
          allowed_iss:
            - http://keycloak:8080/realms/master
            - http://localhost:8080/realms/master
          well_known_template: http://keycloak:8080/realms/master/.well-known/openid-configuration
          realm_roles:
            - customer

  - host: supplier-app
    name: supplier
    port: 8082
    protocol: http
    routes:
      - name: supplier
        strip_path: false
        paths:
          - /supplier
          - /api/security
          - /api/warehouse
    plugins:
      - name: jwt-keycloak
        config:
          allowed_iss:
            - http://keycloak:8080/realms/master
            - http://localhost:8080/realms/master
          well_known_template: http://keycloak:8080/realms/master/.well-known/openid-configuration
          realm_roles:
            - supplier
